services:
  - type: web
    name: forum
    runtime: go
    buildCommand: "go build -o forum main.go"
    startCommand: "./forum"
    envVars:
      - key: PORT
        value: "8080"

      
      - key: DB_HOST
        fromDatabase:
          name: forum-db
          property: host

      - key: DB_USER
        fromDatabase:
          name: forum-db
          property: user

      - key: DB_PASS
        fromDatabase:
          name: forum-db
          property: password

      - key: DB_NAME
        fromDatabase:
          name: forum-db
          property: database

databases:
  - name: forum-db
    databaseName: forumdb
    user: forum_user
    region: oregon